apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ./../../base

images:
- name: PROJECT/IMAGE/BACKEND
  newName: vsirvio/todo-backend
  newTag: 3772f9036f3f0edd68996d80a270c2a133fc383a
- name: PROJECT/IMAGE/FRONTEND
  newName: vsirvio/todo-app
  newTag: 3772f9036f3f0edd68996d80a270c2a133fc383a
