apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ./../../base
- db-backup-cj.yaml

images:
- name: PROJECT/IMAGE/BACKEND
  newName: vsirvio/todo-backend
  newTag: 3065b2149c4c3ceb79f7e11f57fa7a17d6bd4a1a
- name: PROJECT/IMAGE/FRONTEND
  newName: vsirvio/todo-app
  newTag: 3065b2149c4c3ceb79f7e11f57fa7a17d6bd4a1a
