apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ./../../base
- db-backup-cj.yaml

images:
- name: PROJECT/IMAGE/BACKEND
  newName: vsirvio/todo-backend
  newTag: 1bb49f66f6a10529b16e892e37cff2a9097c2840
- name: PROJECT/IMAGE/FRONTEND
  newName: vsirvio/todo-app
  newTag: 1bb49f66f6a10529b16e892e37cff2a9097c2840
