apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ./../../base
- db-backup-cj.yaml

images:
- name: PROJECT/IMAGE/BACKEND
  newName: vsirvio/todo-backend
  newTag: a342597a25f9c342534be2a60736a5f0b76346d0
- name: PROJECT/IMAGE/FRONTEND
  newName: vsirvio/todo-app
  newTag: a342597a25f9c342534be2a60736a5f0b76346d0
