apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ./../../base
- db-backup-cj.yaml

images:
- name: PROJECT/IMAGE/BACKEND
  newName: vsirvio/todo-backend
  newTag: 381255fdfa6839317f578361f0e9930a631b8980
- name: PROJECT/IMAGE/FRONTEND
  newName: vsirvio/todo-app
  newTag: 381255fdfa6839317f578361f0e9930a631b8980
