apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ./../../base
- db-backup-cj.yaml

images:
- name: PROJECT/IMAGE/BACKEND
  newName: vsirvio/todo-backend
  newTag: e27d06e497813dcc3c3e71f2a023d3bbdd878897
- name: PROJECT/IMAGE/FRONTEND
  newName: vsirvio/todo-app
  newTag: e27d06e497813dcc3c3e71f2a023d3bbdd878897
