apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: static-vol
          persistentVolumeClaim:
            claimName: todo-app-static-claim
      containers:
        - name: todo-app
          image: PROJECT/IMAGE/FRONTEND
          env:
          - name: PORT
            value: "3000"
          - name: FRONTEND_ROOT_DIR
            value: "public"
          - name: RANDOM_PICTURE_URL
            value: "https://picsum.photos/256"
          - name: PICTURE_SAVE_DIR
            value: "static"
          - name: PICTURE_FILE_NAME
            value: "image.jpg"
          - name: PICTURE_CHANGE_TIME_IN_MINUTES
            value: "10"
          volumeMounts:
          - name: static-vol
            mountPath: /app/static
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "300Mi"
              cpu: "100m"
  strategy:
    type: Recreate
