apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-dep.yaml
- backend-svc.yaml
- deployment.yaml
- ingress.yaml
- persistentvolumeclaim.yaml
- postgres-secret.yaml
- postgres-sts.yaml
- service.yaml
- todo-backend-wikipedia-cj.yaml
